=== RoamingDot/WeAreLearning/XML/Monster_List.xsd
<xs:schema attributeFormDefault="unqualified" targetNamespace="http://www.w3schools.com" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Monster_List">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Monster">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="Type"/>
			  <xs:element type="xs:string" name="Challenge"/>
              <xs:element type="xs:string" name="Size"/>
              <xs:element type="xs:string" name="Appearance"/>
			  <xs:element type="xs:string" name="Race" minOccurs="0"/>
              <xs:element type="xs:string" name="Alignment"/>
              <xs:element type="xs:string" name="ArmorClass"/>
              <xs:element type="xs:string" name="MinHP"/>
              <xs:element type="xs:string" name="MaxHP"/>
              <xs:element type="xs:string" name="Speed"/>
              <xs:element type="xs:string" name="Strength"/>
              <xs:element type="xs:string" name="Dexterity"/>
              <xs:element type="xs:string" name="Constitution"/>
              <xs:element type="xs:string" name="Intelligence"/>
              <xs:element type="xs:string" name="Wisdom"/>
              <xs:element type="xs:string" name="Charisma"/>
              <xs:element type="xs:string" name="DamageVulnerability" minOccurs="0"/>
              <xs:element type="xs:string" name="DamageResistance" minOccurs="0"/>
			  <xs:element type="xs:string" name="Languages" minOccurs="0"/>
              <xs:element type="xs:string" name="Description" minOccurs="0"/>
              <xs:element name="Senses" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Sense" minOccurs="0" maxOccurs="10"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Actions" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Action" minOccurs="0" maxOccurs="10"/>
					<xs:element type="xs:string" name="LegendaryAction" minOccurs="0" maxOccurs="10"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Abilities" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Ability" minOccurs="0" maxOccurs="10"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="Skills" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Skill" minOccurs="0" maxOccurs="10"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== RoamingDot/WeAreLearning/XML/Monster_List.xml
<?xml version="1.0" encoding="utf-8"?>

<Monster_List xmlns="http://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3schools.com Monster_List.xsd">
  <Monster Type="Ape">
    <Challenge>0.5</Challenge>
    <Size>Medium</Size>
    <Appearance>Beast</Appearance>
    <Alignment>Unaligned</Alignment>
    <ArmorClass>12</ArmorClass>
    <MinHP>9</MinHP>
    <MaxHP>30</MaxHP>
    <Speed>30</Speed>
    <Strength>16</Strength>
    <Dexterity>14</Dexterity>
    <Constitution>14</Constitution>
    <Intelligence>6</Intelligence>
    <Wisdom>12</Wisdom>
    <Charisma>7</Charisma>
    <Senses>
      <Sense>passive Perception 13</Sense>
    </Senses>
    <Actions>
      <Action>Multiattack. The ape makes two fist attacks.</Action>
	  <Action>Fist. Melee Weapon Attack: +5 to hit, reach 5ft., one target. Hit: 6(1d6 +3) bludgeoning damage.</Action>
	  <Action>Rock. Ranged Weapon Attack: +5 to hit, range 25/50ft., one target. Hit: 6(1d6 +3) bludgeoning damage.</Action>
    </Actions>
    <Skills>
      <Skill>Athletics +5</Skill>
    </Skills>
  </Monster>
</Monster_List>
